#!/usr/bin/env bash

set -euo pipefail

for x in bin build; do
    if [ ! -d "$WD/$x" ]; then
        mkdir "$WD/$x"
    fi
done

export TARGET="$WD/bin/main"
export FLAGS=(
    -ccopt -fdelete-null-pointer-checks \
    -ccopt -fshort-enums \
    -ccopt -O3 \
    -ccopt "-std=gnu99" \
    -ccopt -Wall \
    -ccopt -Wbad-function-cast \
    -ccopt -Wcast-align \
    -ccopt "-Wcast-align=strict" \
    -ccopt -Wcast-qual \
    -ccopt -Wconversion \
    -ccopt -Wdate-time \
    -ccopt -Wdouble-promotion \
    -ccopt -Wduplicated-branches \
    -ccopt -Wduplicated-cond \
    -ccopt -Werror \
    -ccopt -Wextra \
    -ccopt -Wfatal-errors \
    -ccopt -Wfloat-equal \
    -ccopt "-Wformat=2" \
    -ccopt -Wformat-signedness \
    -ccopt -Winline \
    -ccopt -Wlogical-op \
    -ccopt -Wmissing-declarations \
    -ccopt -Wmissing-include-dirs \
    -ccopt -Wmissing-prototypes \
    -ccopt -Wnested-externs \
    -ccopt -Wnull-dereference \
    -ccopt -Wpacked \
    -ccopt -Wpedantic \
    -ccopt -Wpointer-arith \
    -ccopt -Wredundant-decls \
    -ccopt -Wshadow \
    -ccopt -Wstack-protector \
    -ccopt -Wstrict-prototypes \
    -ccopt -Wswitch-enum \
    -ccopt -Wtrampolines \
    -ccopt -Wundef \
    -ccopt -Wunused \
    -ccopt -Wunused-macros \
    -ccopt -Wwrite-strings
)

clang-format -i -verbose "$WD/src"/*.h 2>&1 | sed 's/\/.*\///g'
clang-format -i -verbose "$WD/src"/*.c 2>&1 | sed 's/\/.*\///g'

(
    cd "$WD/build"
    cp "$WD/src/"* ./
    ocamlopt \
        -w +1..66 \
        -cc gcc \
        "${FLAGS[@]}" \
        main.ml \
        main_stubs.c \
        -o "$TARGET"
)

"$TARGET"
